export const PlayerDataMap = {
	'first_name': 'First Name',
	'second_name': 'Second Name',
	'status': 'Status',
	'news': 'News',
	'now_cost': 'Price',
	'chance_of_playing_this_round': 'Chance of playing',
	'chance_of_playing_next_round': 'Chance of playing next round',
	'value_form': 'Current value to form',
	'cost_change_start': 'Price change since start',
	'cost_change_event': 'Price change this gameweek',
	'in_dreamteam': 'In dreamteam?',
	'dreamteam_count': 'Times been in dreamteam',
	'selected_by': 'Percentage selected by',
	'form': 'Current form',
	'transfers_out_event': 'Transferred out this gameweek',
	'transfers_in_event': 'Transferred in this gameweek',
	'event_points': 'Points this gameweek',
	'total_points': 'Total points',
	'points_per_game': 'Average points per gameweek',
	'goals_scored': 'Number of goals scored',
	'assists': 'Number of assists',
	'clean_sheets': 'Number of clean sheets',
	'goals_conceded': 'Number of goals conceded',
	'own_goals': 'Own goals',
	'penalties_saved': 'Penalty saves',
	'penalties_missed': 'Penalty misses',
	'yellow_cards': 'Yellow cards',
	'red_cards': 'Red cards',
	'bonus': 'Total number of bonus points',
	'influence': 'Influence',
	'creativity': 'Creativity',
	'threat': 'Threat',
	'team': 'Team'
};
