export const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS';
export const INITIAL_DATA_ERROR = 'INITIAL_DATA_ERROR';
export const FETCHING_DATA = 'FETCHING_DATA';
export const MERGE_INITIAL_DATA = 'MERGE_INITIAL_DATA';
export const GET_MOST_POPULAR = 'GET_MOST_POPULAR';
export const GET_HIGHEST_POINTS = 'GET_HIGHEST_POINTS';
export const GET_BEST_FORM = 'GET_BEST_FORM';
export const GET_BEST_VALUE = 'GET_BEST_VALUE';
