export const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS';
export const INITIAL_DATA_ERROR = 'INITIAL_DATA_ERROR';
export const FETCHING_DATA = 'FETCHING_DATA';
export const MERGE_INITIAL_DATA = 'MERGE_INITIAL_DATA';
export const GET_MOST_POPULAR = 'GET_MOST_POPULAR';
export const GO_TO_URL = 'GO_TO_URL';
